# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']

# Site Settings
title: "RZEmiosło.IT | Konferencja programistyczna w Rzeszowie"
email: "rgdevrze@gmail.com"
description: "Pierwsza konferencja programistyczna w Rzeszowie poświęcona tematyce Software Craftsmanship - dobrym praktykom i metodykom, nie związanymi ściśle z konkretnymi technologiami."
baseurl: "/rzemioslo.it"
url: "http://rzemioslo.it"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "TODO"
googleAnalyticsSiteUrl: "TODO"
siteVerification: "TODO"

# Organizer Info
organizerName: "TODO: maybe not needed"
organizerAlternateName: "TODO: maybe not needed"
organizerDescription: "TODO: maybe not needed"
organizerEmail: "TODO: maybe not needed"
organizerLogo: "TODO: maybe not needed /img/seo/organizer-logo.png"
organizerLink: "TODO: maybe not needed http://lviv.gdg.org.ua/"

# Head
metaKeywords: "RzemiosloIT, Rzeszów, konferencja, programowanie, software, craftsmanship, IT"
twitterAccount: "@RZEmiosloIT"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "TODO: call for papers? https://bit.ly/dfua-c4p"
c4sponsorsUrl: "TODO: /assets/GDG_DevFest_Partnership.pdf"

# Navigation
navigationLinks:
# - {permalink: "/", text: "Home"}
# - {permalink: "/schedule/", text: "Rozkład"}
# - {permalink: "/speakers/", text: "Prelegenci"}
# - {permalink: "/team/", text: "Zespół"}
# - {permalink: "/logistics/", text: "Logistyka"}
#bottomNavigationLinks:
# - {link: "", text: "Zostań prelegentem"}
#rightNavigationButtons:
# - {link: "", text: "Zostań prelegentem"}

# Hero Block
heroImage: "hero.jpg"
#heroButtons:
# - {link: "", text: "Zostań prelegentem"}
# - {permalink: "/#tickets", text: "Kup bilet"}

# About Block
aboutTitle: "O konferencji"
aboutText:
 - "RZEmiosło.IT to pierwsza konferencja programistyczna na Podkarpaciu poświęcona tematyce \"Software Craftsmanship\"."
 - "Nowe technologie pojawiają się i znikają. My wierzymy, że warto inwestować we własne programistyczne rzemiosło, w warsztat, który zawsze będzie aktualny, niezależnie od aktualnych trendów."
 - "Serdecznie zapraszamy!"
#aboutBlock:
# - {title: "Conference", image: "conference.jpg", text: "The biggest Google related event in the country carefully crafted for you by GDG community! Awesome speakers and lots of fun!" }
# - {title: "Workshops", image: "workshop.jpg", text: "Full-day of workshops, hands-on experience, hacking and debugging. Come and tame your favourite technology!" }
# - {title: "Hackathon", image: "hackathon.jpg", text: "Full-day freestyle hackathon! Want some real team building on friday? Grab your team and join our hackathon!" }

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Prelegenci"
rockstarSpeakersButtonText: "Zobacz wszystkich"

# Latest News Block
latestNewsTitle: "Aktualności"

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: ""
twitterHashTag: "rgdevrze"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Location Block
locationBlockTitle: "Lokalizacja"
eventLocationName: "Podkarpacki Park Naukowo-Technologiczny AEROPOLIS"
eventLocationLink: "http://aeropolis.com.pl/pl/"
eventStreetAddress: "Jasionka 954"
eventAddressLocality: ""
eventAddressLocalityRegion: "Rzeszów"
eventPostalCode: "36-002"
eventAddressCountry: "Polska"
eventStartTime: "2017-05-27T09:00"
eventDoorTime: "08:00"
eventEndTime: "2017-05-27T18:00"
eventPlaceCoordinates: "50.1165296, 22.0175096"
mapCenterCoordinates: "50.082178, 22.003305"
mapMobileCenterCoordinates: "50.082178, 22.003305"

# Venue Block
venueBlockTitle: "Miejsce"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Podkarpacki Park Naukowo-Technologiczny AEROPOLIS"
venueFeatures: ["Piękna nowa sala konferencyjna", "Położona tuż przy lotnisku Jasionka"]

# Partners Block
organizersTitle: "Organizatorzy"
partnersTitle: "Partnerzy"
partnersC4sponsorsButton: "Zostań sponsorem"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Zapisz się do newslettera"
subscribeAction: "//twitter.us15.list-manage.com/subscribe/post?u=4ae7f76665dd80a02a0159897&amp;id=75e4a841a1"
subscribeInfo: "Liczba biletów jest ograniczona. Rejestracja rozpocznie się wkrótce..."

# Tickets Block
ticketsTitle: "Bilety"
ticketsInfo: "Bilety umożliwiają wstęp na wszystkie prezentacje, przerwy kawowe, lunch i afterparty. Nocleg nie jest wliczony w cenę biletu."
#ticketsOffers:
# -
#  name: "Early Bird"
#  price: "350"
#  priceCurrency: "UAH"
#  ticketsNumber: "150"
#  ribbon: "-5%"
#  buyButtonLink: "http://dfua.ticketforevent.com/"
#  buyButtonText: "Buy Now"
#  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
#  validFrom: "2014-08-25T10:00"
#  validThrough: "2014-09-30T23:59"
# -
#  name: "Last Chance"
#  price: "450"
#  priceCurrency: "UAH"
#  ticketsNumber: "100"
#  ribbon: "-20%"
#  featured: true
#  buyButtonLink: "http://dfua.ticketforevent.com/"
#  buyButtonText: "Buy Now"
#  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
#  validFrom: "2014-10-01T00:00"
#  validThrough: "2014-10-23T23:59"
#  disabled: true
# -
#  name: "Student"
#  price: "200"
#  priceCurrency: "UAH"
#  ticketsNumber: "50"
#  buyButtonLink: "http://dfua.ticketforevent.com/"
#  buyButtonText: "Buy Now"
#  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
#  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
#  validFrom: "2014-08-20T10:00"
#  validThrough: "2014-10-23T23:59"
#  soldOut: true
#  soldOutText: "Sold Out"

# Footer
socialLinks:
 - {link: "https://plus.google.com/b/102444623953913144164", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=rgdevrze", icon: "twitter"}
 - {link: "https://facebook.com/rgdev.rze/", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Linki"
  links:
   - {link: "https://www.meetup.com/rg-dev/", text: "rg-dev"}
 -
  title: "Kontakt"
  links:
   - {link: "mailto:rgdevrze@gmail.com", text: "rgdevrze@gmail.com"}
 -
  title: "FAQ"
  links:
   - {permalink: "", text: "Regulamin"}
   - {permalink: "", text: "FAQ"}

# Blog
blogTitle: "Aktualności"
blogCommentsEnabled: true
discusShortName: "rzemiosloit"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Lviv"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
 - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
 - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
